### ISSUE TITLE
Add color info to  mnc_operators.json

### ISSUE THREAD

**Issue by Gitschubser** [andymckay/mobile-codes#22]
Is it possible to add the color from the provider to mnc_operators.json?
This could help some projects to use this information to show the cells in this color from the provider.

Example:
["262", "01", "Telekom Deutschland GmbH", "Telekom Deutschland GmbH", "#e20074"],
["262", "02", "Vodafone D2 GmbH", "Vodafone D2 GmbH", "#FF0000"],
["262", "03", "E-Plus Mobilfunk GmbH & Co. KG", "E-Plus Mobilfunk GmbH & Co. KG","#00603F"],

**Comment by andymckay** [comment]
Colour? Providers have official colours assigned? What standard is this?

I can't seen any value in having that information, maybe a seperate lookup in a seperate library would make sense.

**Comment by andymckay** [comment]
I don't intend to maintain this library anymore. I've added a note to the readme and sending this comment to people who have an issue on the library so you can fork it or do whatever you'd like.
