### ISSUE TITLE
"234", "&#160;?"

### ISSUE THREAD

**Issue by Gitschubser** [andymckay/mobile-codes#23]
Is &#160;? a wrong value?

**Comment by andymckay** [comment]
Looks like it, @jaredkerim did that come from your import script?

**Comment by andymckay** [comment]
https://github.com/andymckay/mobile-codes/blob/3998caf9be9eae44254f29d738a68156fad29b53/mobile_codes/json/mnc_operators.json#L215

**Comment by jaredkerim** [comment]
Hrmm yeah looks like an unparsed HTML escape code.  I'll try to reimport and update.

**Comment by andymckay** [comment]
I don't intend to maintain this library anymore. I've added a note to the readme and sending this comment to people who have an issue on the library so you can fork it or do whatever you'd like.
